name = "sveltekit"
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-02-14"

main = "./.cloudflare/worker.js"
[site]
bucket = "./.cloudflare/public"

[build]
command = "npm run build"
[vars]
account_id = ""